openapi: 3.2.0
info:
  title: MolTrust Interaction API
  version: '2.5'
tags:
- name: Interaction
paths:
  /interaction/validate-signing:
    post:
      summary: Validate Signing Endpoint
      description: Validate interaction proof signing sequence. Tech Spec v0.2.2.
      operationId: validate_signing_endpoint_interaction_validate_signing_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Interaction
