openapi: 3.2.0
info:
  title: MolTrust Webhooks API
  version: '2.5'
tags:
- name: Webhooks
paths:
  /webhooks/payment:
    post:
      summary: Payment Webhook
      description: Receive Basescan webhook for incoming USDC payments to MolTrust wallet.
      operationId: payment_webhook_webhooks_payment_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Webhooks
