openapi: 3.2.0
info:
  title: MolTrust Stats API
  version: '2.5'
tags:
- name: Stats
paths:
  /stats:
    get:
      summary: Public Stats
      operationId: public_stats_stats_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Stats
